# Numpy ( Numrical Python)
    Numrical Python is a library for working with array and mathematical operation in Python. It is a fundamental packages for scientific computing with Python and is widely used in various fields. 
    

NumPy library provides the mathematical operation at once on the array for computation, it is Used for linear algebra, random number generation , and many more. Numpy provides support for large multi-dimensional array and matrices, which are important for scientific computation.
      It is faster than did the operation on the Python list. It also works with libraries such as Pandas, Matplotlib  , Scipy, etc.

# Installation
    The Numrical Python Libraries installed by using the command line " !pip install numpy" or "pip install numpy" in the python command propmt.

# Array in the numpy
    In the ndarray(), the array have any dimensional including 1D, 2D, 3D,....
    Item of the array must be same data type. It is mutable data set, its mean we can add the data after creation thr array

In [1]:
#Creation of array
import numpy as np

x = np.array([1,2,3,4,5])  # we creating the array using the list or tuple
print(x)

[1 2 3 4 5]


In [2]:
print(type(x))

<class 'numpy.ndarray'>


In [3]:
#np.zeros()
xx = np.zeros((2,3)) # Creating the matric of zeros of 2 row and 3 column
print(xx)

[[0. 0. 0.]
 [0. 0. 0.]]


In [4]:
 xxx = np.ones((3,4)) # creating the matric of 1 with 3 raw and 4 column
print(xxx)
print(type(xxx))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<class 'numpy.ndarray'>


In [5]:
# we can create the array with a perticular rang by using the np.arange()

xxxx = np.arange(1,10,2) # craeting the array in range 1 to 10(excluded) with difference of 2
print(xxxx)

[1 3 5 7 9]


In [6]:
# taking the sample between specific range of fixed difference
x1 = np.linspace(1,10,4) # 4 sample between 1 to 10
print(x1)

[ 1.  4.  7. 10.]


# Indexing and Slicing

In [7]:
# Indexing 
# we have a list ,from the list we can access the single element uasing index of the element
print(x1[1])
print(f'{x[1]}is element of the {x}')

4.0
2is element of the [1 2 3 4 5]


In [8]:
# Slicing 
# we can access the elemnet of list in between range . its mean we can access the elemnt of of spefic range

In [9]:
print(x[1:3])

[2 3]


In [10]:
# Extract the first two rows and all columns
print(xx[:2, :])  

[[0. 0. 0.]
 [0. 0. 0.]]


# Arithmetic Operations on NumPy Arrays:
NumPy allows you to perform element-wise arithmetic operations on arrays efficiently without the need for explicit loops
- addition
- Substraction
- multiplication
- division
            
    we can done arithmetic operation on array directly
    also we can get sq.root ,sin(), exponential()

In [11]:
# Addition

print(x)
print(x+2 )# we added the 2 in all element 
print(xx+2)
x_3 =xxx+3
print(f'original{xxx} after adding the element {x_3}')

[1 2 3 4 5]
[3 4 5 6 7]
[[2. 2. 2.]
 [2. 2. 2.]]
original[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] after adding the element [[4. 4. 4. 4.]
 [4. 4. 4. 4.]
 [4. 4. 4. 4.]]


In [12]:
# Subtraction
print(f'Original{x} after subtraction 2 from x={x-2}')

print(f'Original{xx} after subtraction  from xx={xx-5}')  #xx is np.zeros( ) array   (2D array)

Original[1 2 3 4 5] after subtraction 2 from x=[-1  0  1  2  3]
Original[[0. 0. 0.]
 [0. 0. 0.]] after subtraction  from xx=[[-5. -5. -5.]
 [-5. -5. -5.]]


In [13]:
# Division
print(f'Original{x} after  Division 4 from x={x/4}')

Original[1 2 3 4 5] after  Division 4 from x=[0.25 0.5  0.75 1.   1.25]


In [14]:
# Multiplication

print(f'Original{x} after multiplication 2 from x={x*2}')

Original[1 2 3 4 5] after multiplication 2 from x=[ 2  4  6  8 10]


In [15]:
#sq.root()
sq = np.sqrt(x)
print(sq)
print(f' Oroginal {xxxx} after taking the square root = {np.sqrt(xxxx)}')

[1.         1.41421356 1.73205081 2.         2.23606798]
 Oroginal [1 3 5 7 9] after taking the square root = [1.         1.73205081 2.23606798 2.64575131 3.        ]


In [16]:
#sin()
print(f'orignal{x} after taking sin() {np.sin(x)}')

orignal[1 2 3 4 5] after taking sin() [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [17]:
# Exponential
print(f'original {xxx} after taking exponential {np.exp(xxx)}')

original [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] after taking exponential [[2.71828183 2.71828183 2.71828183 2.71828183]
 [2.71828183 2.71828183 2.71828183 2.71828183]
 [2.71828183 2.71828183 2.71828183 2.71828183]]


In [18]:
c =[[1,2,3,4],[4,5,6,7],[7,8,9,10]]
v =np.array(c)

# Array Shape and  Reshape
    Checking array dimensions with .shape and .ndim.
    Changing array shape with .reshape(), .flatten(), .transpose().
    Concatenating and splitting arrays using np.concatenate(), np.vstack(), np.hstack(), np.split().

In [19]:
# we can check the dimension , shape of the array
print(v)
print(v.shape)  # it will be 3 ,3 of three column and 3 row

print(v.ndim) # it will be give the dimensional of the array

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
(3, 4)
2


In [20]:
print(f'original {v} and after reshape {v.reshape(4,3)}')
# origonal matrix conatain 3 row and 4 column, after reshape we converted into 4 row and 3 column

original [[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]] and after reshape [[ 1  2  3]
 [ 4  4  5]
 [ 6  7  7]
 [ 8  9 10]]


In [21]:
print(v.flatten())
# this function convert a matrix into a single array

[ 1  2  3  4  4  5  6  7  7  8  9 10]


In [22]:
v.transpose()
# taking th tranpose of the matric

array([[ 1,  4,  7],
       [ 2,  5,  8],
       [ 3,  6,  9],
       [ 4,  7, 10]])

In [23]:

z=np.concatenate(v)

In [24]:
print(z)

[ 1  2  3  4  4  5  6  7  7  8  9 10]


In [25]:
np.hstack(v)

array([ 1,  2,  3,  4,  4,  5,  6,  7,  7,  8,  9, 10])

In [26]:
np.vstack(v)

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 7,  8,  9, 10]])

In [27]:
a,b,c=np.split(v,3)

In [28]:
a

array([[1, 2, 3, 4]])

# Broadcasting in Numpy
- Broadcasting is the powerful tool that allowa to operation betwee array of different shapes. It enables efficient computation without the needd to explicitly create intermediate arrays, leading to significant performance gains.
-  key rules of broadcasting : Rule 1 Shape campatibility
Arrays must have compatible shapes for broadcasting to occur.
Two dimensions are compatible when
- They are equal
- One of the is Rule 2: ImplicitExpansion
  Dimension of size 1 are stretched or 'broadcasting' to match the corresponding dimension of the other array.

In [29]:
x = np.array([2,4,6]) # shape(3,)
y = np.array([3]) #shape(1)
c = x+y

print('Brodcasting is=',c)

Brodcasting is= [5 7 9]


In [30]:
# Scalar brodcasting
x = np.array([2,4,6]) 
a = 2
d = x*a

print(f'Scalar broadcasting is = {d}')

Scalar broadcasting is = [ 4  8 12]


In [31]:
#array bradcasting
X = np.array([[10,20,30],[40,50,60]])
Y = np.array([1,2,3])

c = X+Y
print("Array Broadcasting:\n", c)

Array Broadcasting:
 [[11 22 33]
 [41 52 63]]


# Array Manipulation Indexing and slicing: understanding multi-dimensional arrays. Masking (logical indexing based on conditions). Fancy indexing (using arrays of indices to select elements).

In [32]:
#indexing
import numpy as np
ar = np.array([[1, 2, 3], [4, 5 ,6]])
# Accesing the elements
print(ar[0,2])
print(ar[0,1])
print(ar[1,2])


3
2
6


In [33]:
# Slicing 
print(ar[0:2])
print(ar[:,1])
print(ar[1,1:])

[[1 2 3]
 [4 5 6]]
[2 5]
[5 6]


# Masking 
    Logical Indexing
- Masking is also known as boolean indexing  ,ia a powerful technique in NunPy that allows user to select elements from an array base on boolean condition.

In [34]:
a1 = np.array([1,2,3,4,5,6,7,8,9])
mk =a1 != 2  # not equal to 2
print(a1[mk])


[1 3 4 5 6 7 8 9]


In [35]:
# using same arrray
mask2 =a1>2 # only greater than 2
print(a1[mask2])

[3 4 5 6 7 8 9]


# Fancy Indexing
Fancy indexing allows for flexible selection of elements using arrays if indices.

In [36]:
df = np.array([10,20,30,40,50,60])
indices = np.array([0,2,5])


selected_ele = df[indices]
print(selected_ele)

[10 30 60]


In [37]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
r =np.array([0,2])   # row index
c = np.array([1,2])# column index



selected = a2[r,c]

print(selected)

[2 9]


# Mathematical Functions
    -universal fun = ufuncs
    -1) np.add()
    -2) np.subtract()
    np.multiply()

    Statistical Functions
        -np.mean()
        np.meadian()
        np.std()
        np.var()
        np.min()
        np.max()
        np.mode()
    Linear algebra fun
        np.dot()
        np.matmul()
        np.linalg.inv()
        np.linalg.eig()
        

# Universal Functions

In [38]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

res=np.add(a1,a2)

print(res)

[5 7 9]


In [39]:
result = np.subtract(a1 , a2)
print(result)

[-3 -3 -3]


In [40]:
res = np.multiply(a1,a2)

print(res)

[ 4 10 18]


In [41]:
res = np.log(a1)
print(res)

[0.         0.69314718 1.09861229]


# Statistical Functions 
    These fnction helps to summarise data and analyse data.

In [42]:
aq = np.array([5,10,15,20,25,30,35,40,45,50])

In [43]:
mean_val = np.mean(aq)

In [44]:
print(mean_val)

27.5


In [45]:
# Standard deviation


sdt = np.std(aq)

print('Standard deviation:',sdt)

Standard deviation: 14.361406616345072


In [46]:
# Median
print('Median :',np.median(aq))

Median : 27.5


In [47]:
# variance
print('variance',np.var(aq))

variance 206.25


In [48]:
#Minimum valu
print('Minimum',np.min(aq))

Minimum 5


In [49]:
# Maxima
print('maximum',np.max(aq))

maximum 50


# Liinear Albgebra Funs

In [50]:
#np.dot()  finding dot product of two array
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])


print(np.dot(a1,a2))

32


# matmul()
 matrix muultiplication of two array

In [51]:
m1 = np.array([[6,7],[8,9]])
m2 = np.array([[1,2,3,],[4,5,6]])



prod = np.matmul(m1,m2)
print(prod)

[[34 47 60]
 [44 61 78]]


 np.linalg.inv()
     calculate the inverse of a square matrix
     

In [52]:

mat = np.array([[1,2],[3,4]])
inv = np.linalg.inv(mat)
print(inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


# np.linalg.eig()]
    computes the eigens values and eigen values vector of a square matrix


In [53]:

a = np.array([[1, 2], [3, 4]]) 
w, v = np.linalg.eig(a)

print("Eigenvalues:", w)  
print("Eigenvectors:\n", v)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


# Random Number Generation:-
Random number generation is the process of creating a sequence of numbers that appear to be random.


In [54]:
np.random.random((3,4))

array([[0.12011724, 0.93268174, 0.7624758 , 0.14954996],
       [0.5409422 , 0.53891434, 0.72100726, 0.42398601],
       [0.81605267, 0.7403718 , 0.70195164, 0.50605921]])

# rand():
It will generate random value between 0-l and reshape(x,y) to craete x*y matrix.

In [55]:
data = np.random.rand(1,20)
print(data)

[[0.16143968 0.48969055 0.67089845 0.63373816 0.06784223 0.95379868
  0.68167845 0.9532211  0.92116996 0.73588149 0.71052536 0.86180406
  0.26804817 0.06536106 0.1839638  0.84875118 0.43630742 0.3381219
  0.56498884 0.04913784]]


In [56]:
len(data)

1

# np.random.randint():-
Generates random integers from a given range


In [57]:
random_int = np.random.randint(0,11,6)
print(random_int)

[ 9  3 10  1  9  0]


# np.random.randn():
Generates random numbers from a standard normal distribution (mean 0, standard deviation 1).

In [58]:
random_normal = np.random.randn(10)
print(random_normal)

[-0.80840429  0.38074304 -0.02169995  1.83996045 -1.63082558  0.81990798
  0.90714794 -1.80688357  0.25186156  1.0483116 ]


# ranf() :
generates random floats in the half-open interval [0.0, 1.0).

In [59]:

random_f = np.random.ranf(10)
random_f

array([9.71833564e-01, 8.14143238e-01, 3.49369416e-01, 3.67274980e-01,
       1.55722848e-01, 8.57625390e-01, 7.27170640e-01, 4.85739641e-04,
       7.27823878e-01, 9.62123378e-01])

# Seeding Random Geration
- Sets the seed for the random number generator. This ensure that the same sdeqence of random number is generated each time the code is run with the same seed.

In [66]:
ar = np.random.seed(15)
ar1 = np.random.rand(5)
print(ar1)

[0.8488177  0.17889592 0.05436321 0.36153845 0.27540093]


# Random Sampling , shuffling and Permutation
-np.random.choice() - Draws a given number of samples from the a given array or sequence with or without replacment i.e. SRSWR or SRSWOR

In [70]:
# For With Replacement SRSWR
df = np.array([1,2,3,4,5,6,7,8,9])
sp = np.random.choice(df,5,replace =True)
print(sp)

[9 6 7 3 9]


In [72]:
# For without replacement SRSWOR
sp1 = np.random.choice(df,5,replace = False)
print(sp1)

[7 5 2 6 4]


In [76]:
# Shuffling
# Shuffles the element of array

ar = np.array([1,2,3,4,5,6])
sample1 = np.random.shuffle(ar)
print(ar)

[1 6 5 2 3 4]


### Used in Vectorization

In [77]:
#adding a scalar to an array
s = 8
r = ar + s

In [78]:
print(r)

[ 9 14 13 10 11 12]
